{
 "title": "click event analysis",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Max Click Count - /help",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`sql-demo`",
     "rawSql": "SELECT MAX(count) FROM `sql-demo`.click_event_report WHERE page = '/help' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Max Click Count - /index",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`sql-demo`",
     "rawSql": "SELECT MAX(count) FROM `sql-demo`.click_event_report WHERE page = '/index' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Max Click Count - /shop",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`sql-demo`",
     "rawSql": "SELECT MAX(count) FROM `sql-demo`.click_event_report WHERE page = '/shop' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Max Click Count - /jobs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`sql-demo`",
     "rawSql": "SELECT MAX(count) FROM `sql-demo`.click_event_report WHERE page = '/jobs' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Max Click Count - /about",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`sql-demo`",
     "rawSql": "SELECT MAX(count) FROM `sql-demo`.click_event_report WHERE page = '/about' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Max Click Count - /news",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`sql-demo`",
     "rawSql": "SELECT MAX(count) FROM `sql-demo`.click_event_report WHERE page = '/news' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Click Counts per 15 sec",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT\n  $__timeGroupAlias(window_start,'15s'),\n  sum(count),\n  'sum' as value,\n  page\nFROM click_event_report\nWHERE $__timeFilter(window_start)\nGROUP BY time, page\nORDER BY time"
    }
   ]
  }
 ]
}